language: java
sudo: true
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:

    - stage: build
      script:
        - mvn clean verify

    - stage: publish
      if: branch = master AND type = push AND fork = false
      script:
        - bash deploy-to-maven-central.sh